version: '3.8'

services:
  langit-db:
    container_name: langit-db
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: langit-password
      POSTGRES_DB: langit
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    container_name: langit-be
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - langit-db
    environment:
      NODE_ENV: staging
    command: ['node', 'dist/src/app.js']
    # volumes:
    # - .:/usr/src/app:ro
    restart: always
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email soultanmuh@gmail.com --agree-tos --no-eff-email --force-renewal -d langitapi.blockchainworks.id

volumes:
  db-data:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/LangitApi/src/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/LangitApi/dhparam
      o: bind

networks:
  app-network:
    driver: bridge
